services:

  db:
    image: postgres:17
    container_name: produtos-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: produtosdb
    ports:
      - "${POSTGRES_HOST_PORT:-5433}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d produtosdb"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build: .
    container_name: produtos-api
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__Postgres: "Host=db;Port=5432;Database=produtosdb;Username=postgres;Password=postgres123"
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata: