CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "Categorias" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nome" text NOT NULL,
    CONSTRAINT "PK_Categorias" PRIMARY KEY ("Id")
);

CREATE TABLE "Produtos" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nome" text NOT NULL,
    "Preco" numeric NOT NULL,
    "CategoriaId" integer NOT NULL,
    CONSTRAINT "PK_Produtos" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Produtos_Categorias_CategoriaId" FOREIGN KEY ("CategoriaId") REFERENCES "Categorias" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_Produtos_CategoriaId" ON "Produtos" ("CategoriaId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260908164222_InitialPostgres', '8.0.0');

COMMIT;

